branches:
  - main

plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/changelog"
  - - "@semantic-release/exec"
    - prepareCmd: "cargo install cargo-edit && cargo set-version ${nextRelease.version} && cargo check --quiet"
      publishCmd: "echo 'Release ${nextRelease.version} prepared successfully'"
  - - "@semantic-release/git"
    - assets:
        - "Cargo.toml"
        - "Cargo.lock" 
        - "CHANGELOG.md"
      message: "chore(release): bump version to ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"
  - "@semantic-release/github"

preset: "conventionalcommits"