name: CI

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

env:
  CARGO_TERM_COLOR: always
jobs:
  build_and_test_linux:
    name: Build & Test (Linux)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Install OpenSSL
        run: sudo apt-get install -y libssl-dev
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
      - name: Run clippy
        run: cargo clippy -- -W clippy::pedantic -D warnings
      - name: Check formatting
        run: cargo fmt -- --check
      # - name: Security audit # Uncomment if cargo-audit is added
      #   run: cargo audit
  build_and_test_macos_intel:
    name: Build & Test (macOS x86_64-apple-darwin)
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Set up OpenSSL for target architecture
        run: |
          brew install openssl@3
          echo "OPENSSL_DIR=$(brew --prefix openssl@3)" >> $GITHUB_ENV
          echo "OPENSSL_LIB_DIR=$(brew --prefix openssl@3)/lib" >> $GITHUB_ENV
          echo "OPENSSL_INCLUDE_DIR=$(brew --prefix openssl@3)/include" >> $GITHUB_ENV
          echo "PKG_CONFIG_PATH=$OPENSSL_LIB_DIR/pkgconfig" >> $GITHUB_ENV
        shell: bash
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
      - name: Run clippy
        run: cargo clippy -- -W clippy::pedantic -D warnings
      - name: Check formatting
        run: cargo fmt -- --check
  build_and_test_macos_arm:
    name: Build & Test (macOS aarch64-apple-darwin)
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Set up OpenSSL for target architecture
        run: |
          brew install openssl@3
          echo "OPENSSL_DIR=$(brew --prefix openssl@3)" >> $GITHUB_ENV
          echo "OPENSSL_LIB_DIR=$(brew --prefix openssl@3)/lib" >> $GITHUB_ENV
          echo "OPENSSL_INCLUDE_DIR=$(brew --prefix openssl@3)/include" >> $GITHUB_ENV
          echo "PKG_CONFIG_PATH=$OPENSSL_LIB_DIR/pkgconfig" >> $GITHUB_ENV
        shell: bash
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
      - name: Run clippy
        run: cargo clippy -- -W clippy::pedantic -D warnings
      - name: Check formatting
        run: cargo fmt -- --check
